# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe363084df926e92f39e203ee9e282d29dab2fd0d618ec3414967f78886c9be6a0702aec65e52efb88447e528ccfd25f39040fd296bbbde658fcc97301036e6c

test:
  secret_key_base: 0b47bafb8d7eefe2efe757bee69ab86e0037ee41df908f1535c458003fc7fd0fadf4b1bee4996e9080419ad69e452781fbff16d2281dd4b3d9700cf263eb787c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
